package io.softwarecrafter.annotation.sample;

import io.bytesbiter.annotation.sample.PersonBuilder;

public class Main {

    public static void main(String[] args) {
        /**
         * Instantiating a new object of class Person the old fashioned way with new keyword.
         */
        Person person1 = new Person();

        /**
         * Instantiating a new object with our newly created PersonBuilder class, which is being generated by annotations
         * within the Person class file at the setter methods.
         *
         * @see Person
         */
        Person person2 = new PersonBuilder()
                .setAge(12)
                .setFirstName("First Name")
                .setLastName("Last Name")
                .build();
    }
}
